services:
  nginx:
    image: tugboatqa/nginx
    default: true

    commands:
      init:
        - curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
        - bash nodesource_setup.sh
        - apt install nodejs
        - npm install

      build:
        - npm run build
        - ln -snf "${TUGBOAT_ROOT}/build" "${DOCROOT}"
